modLoader = "javafml"
loaderVersion = "[${forge_version},)"
issueTrackerURL = "https://github.com/ajh123/Sams-Bits/issues"
license = "AGPL-3.0"

[[mods]]
modId = "sams_bits"
version = "${version}"
displayName = "Sam's Bits"
authors = "Samuel Hulme"
description = '''
Extra stuff that I want for the Create mod and Minecraft.
'''
logoFile = "icon.png"

[[dependencies.sams_bits]]
modId = "forge"
mandatory = true
versionRange = "[${forge_version},)"
ordering = "NONE"
side = "BOTH"

[[dependencies.sams_bits]]
modId = "minecraft"
mandatory = true
versionRange = "${minecraft_version}"
ordering = "NONE"
side = "BOTH"

[[dependencies.sams_bits]]
modId="create"
mandatory=true
versionRange="${create_version}"
ordering="NONE"
side="BOTH"